name       : haskell-ObjectName
version    : 1.1.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/ObjectName-1.1.0.1/ObjectName-1.1.0.1.tar.gz : 72dbef237580fd4e8567de2de752835bbadd3629f486d1586486d49a49aad210
license    : BSD-3-Clause
component  : programming
summary    : This tiny package contains the class ObjectName, which corresponds to the general notion of explicitly handled identifiers for API objects
description: |
    This tiny package contains the class ObjectName, which corresponds to the general notion of explicitly handled identifiers for API objects
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 ObjectName-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/ObjectName-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/ObjectName-$version/*.a
