name       : haskell-ObjectName
version    : 1.1.0.1
release    : 5
source     :
    - http://hackage.haskell.org/package/ObjectName-1.1.0.1/ObjectName-1.1.0.1.tar.gz : 72dbef237580fd4e8567de2de752835bbadd3629f486d1586486d49a49aad210
license    : BSD-3-Clause
component  : programming.haskell
summary    : This tiny package contains the class ObjectName, which corresponds to the general notion of explicitly handled identifiers for API objects
description: |
    This tiny package contains the class ObjectName, which corresponds to the general notion of explicitly handled identifiers for API objects
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
